# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
version: 2
project_name: docker-machine-driver-otccce
before:
  hooks:
    - go mod tidy

builds:
  - binary: docker-machine-driver-otccce
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    dir: .
    main: .
    ldflags:
      - -s -w
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - format: tar.gz
    name_template: "{{ .Binary }}-{{ .Version }}-linux-amd64"
    files: []
    wrap_in_directory: false
    allow_different_binary_count: true

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

release:
  draft: true
  github:
    owner: wolfslicht
    name: rancher-node-engine-driver-sotc
  name_template: "v{{ .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge' 