# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
version: 2
project_name: docker-machine-driver-otccce
before:
  hooks:
    # this is just an example and not a requirement for provider building/publishing
    - go mod tidy
builds:
  - binary: rancher-node-engine-driver-sotc
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - bin/*

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  # Visit your project's GitHub Releases page to publish this release.
  draft: true
  github:
    owner: sc-opentelekomcloud
    name: rancher-node-engine-driver-sotc

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge' 