# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
version: 2
project_name: docker-machine-driver-otccce
before:
  hooks:
    # this is just an example and not a requirement for provider building/publishing
    - go mod tidy
    - make build-linux

builds:
  - binary: docker-machine-driver-otccce
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    dir: .
    main: .
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*  # Don't include any extra files
    wrap_in_directory: false
    allow_different_binary_count: true

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

release:
  draft: true
  github:
    owner: wolfslicht
    name: rancher-node-engine-driver-sotc

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge' 